spring:
  application:
    name: Spring Cloud
  profiles:
    active: dev

  datasource:
    url: ${springcloud.dburl}
    username: ${springcloud.dbusername}
    password: ${springcloud.dbpassword}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        hbm2ddl:
          auto: update


  mvc:
    hiddenmethod:
      filter:
        enabled: true